### ISSUE TITLE
API key is opened in source code calc_main.py:65

### ISSUE THREAD

**Issue by dfcat** [dawnclass/DFO_Gear_Calculator#10]
According to [terms of neople open api](https://developers.neople.co.kr/contents/policy), opening api key is not permitted

> 제 5 조 (이용자의 의무)
> ① 이용자는 자신이 발급 받은 API Key를 타인에게 제공, 공개하거나 공유할 수 없습니다.

It cause overuse or abuse your key by cracker. 

You released your key in github already, it's better to assign new key after cancel old key than change code to hide key. But, it derive  error in old version that already downloaded.

**Comment by dawnclass** [comment]
Thank you for your advice. I'm developing v4.0, and I'll change and hide my api key.
